CREATE TABLE users(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    version BIGINT NOT NULL
);

CREATE TABLE bank_accounts(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL,
    balance NUMERIC(19, 2) NOT NULL,
    status VARCHAR(255) NOT NULL,

    CONSTRAINT fk_bank_accounts_owner
        FOREIGN KEY (owner_id)
            REFERENCES users(id),

    CONSTRAINT chk_bank_accounts_balance
        CHECK (balance >= 0)
);

CREATE TABLE transactions(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_account_id BIGINT NOT NULL,
    to_account_id BIGINT NOT NULL,
    amount NUMERIC(19, 2) NOT NULL,
    created_at TIMESTAMP NOT NULL,

    CONSTRAINT chk_transactions_amount
        CHECK (amount > 0),

    CONSTRAINT fk_transaction_from
        FOREIGN KEY (from_account_id)
            REFERENCES bank_accounts(id),

    CONSTRAINT fk_transaction_to
        FOREIGN KEY (to_account_id)
            REFERENCES bank_accounts(id),

    CONSTRAINT chk_different_accounts
        CHECK (from_account_id <> to_account_id)
);
